version: '3.9'

services:
    postgis:
        image: postgis/postgis
        container_name: postgis_container
        restart: on-failure
        environment: 
            - POSTGRES_DB=admin
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        networks: 
            - main
        ports: 
            - "5432:5432"
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data 
            
networks: 
    main:
        
volumes: 
    data:
